"""empty message

Revision ID: 0f4cdff809b0
Revises: ae6bbffe608c
Create Date: 2018-12-13 13:59:10.502618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f4cdff809b0'
down_revision = 'ae6bbffe608c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
