"""empty message

Revision ID: 6bd48e0fc364
Revises: 
Create Date: 2018-10-11 14:38:36.830783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd48e0fc364'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('phone_SDKVersion', sa.String(length=128), nullable=True),
    sa.Column('errMsg', sa.String(length=128), nullable=True),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('phone_fontSizeSetting', sa.String(length=128), nullable=True),
    sa.Column('user_language', sa.String(length=128), nullable=True),
    sa.Column('phone_name', sa.String(length=128), nullable=True),
    sa.Column('phone_pixelRatio', sa.String(length=128), nullable=True),
    sa.Column('phone_platform', sa.String(length=128), nullable=True),
    sa.Column('phone_screenHeight', sa.String(length=128), nullable=True),
    sa.Column('phone_screenWidth', sa.String(length=128), nullable=True),
    sa.Column('phone_system', sa.String(length=128), nullable=True),
    sa.Column('phone_version', sa.String(length=128), nullable=True),
    sa.Column('phone_windowHeight', sa.String(length=128), nullable=True),
    sa.Column('phone_windowWidth', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UnionID', sa.String(length=128), nullable=True),
    sa.Column('wxId', sa.String(length=128), nullable=True),
    sa.Column('xcxId', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('registed_on', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Unicode(length=30), nullable=True),
    sa.Column('nickName', sa.Unicode(length=30), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('avatarUrl', sa.String(length=128), nullable=True),
    sa.Column('parent_userid', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Unicode(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('qr_url', sa.String(length=128), nullable=True),
    sa.Column('qr_expireDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_vehicle',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_lpn', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fs_history',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicleId', sa.Integer(), nullable=True),
    sa.Column('tranDate', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_his_pic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuelHisId', sa.Integer(), nullable=True),
    sa.Column('picUrl', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_history',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicleId', sa.Integer(), nullable=True),
    sa.Column('tranDate', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('fuelvolume', sa.Float(), nullable=True),
    sa.Column('fuelTypeId', sa.Integer(), nullable=True),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.Column('tankStatus', sa.Integer(), nullable=True),
    sa.Column('fuelAlert', sa.Boolean(), nullable=False),
    sa.Column('tankAlert', sa.Boolean(), nullable=True),
    sa.Column('calculated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicleId', sa.Integer(), nullable=True),
    sa.Column('startDate', sa.DateTime(), nullable=True),
    sa.Column('endDate', sa.DateTime(), nullable=True),
    sa.Column('fuelvolume', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('costPerKm', sa.Float(), nullable=True),
    sa.Column('kmPerDay', sa.Float(), nullable=True),
    sa.Column('fuelRate', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('day_diff', sa.Float(), nullable=True),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.Column('fuelHisId', sa.Integer(), nullable=True),
    sa.Column('fuelHisIdEnd', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuelTypeName', sa.String(length=50, convert_unicode=True), nullable=True),
    sa.Column('notes', sa.String(length=100), nullable=True),
    sa.Column('sort_seq', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('period_fuel_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodType', sa.String(length=10), nullable=True),
    sa.Column('periodName', sa.String(length=25), nullable=True),
    sa.Column('fuelPeriod', sa.DateTime(), nullable=True),
    sa.Column('vehicleId', sa.Integer(), nullable=True),
    sa.Column('startDate', sa.DateTime(), nullable=True),
    sa.Column('endDate', sa.DateTime(), nullable=True),
    sa.Column('fuelvolume', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('costPerKm', sa.Float(), nullable=True),
    sa.Column('kmPerDay', sa.Float(), nullable=True),
    sa.Column('fuelRate', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('day_diff', sa.Float(), nullable=True),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.Column('fuelHisId', sa.Integer(), nullable=True),
    sa.Column('fuelHisIdEnd', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_company',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_group',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_vehicles',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicleName', sa.Unicode(length=50), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('engine', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('tankVol', sa.Float(), nullable=True),
    sa.Column('calTankVol', sa.Float(), nullable=True),
    sa.Column('startMileage', sa.Float(), nullable=True),
    sa.Column('lastMileage', sa.Float(), nullable=True),
    sa.Column('lastFuelRate', sa.Float(), nullable=True),
    sa.Column('lastFuelDate', sa.DateTime(), nullable=True),
    sa.Column('lpn', sa.Unicode(length=50), nullable=True),
    sa.Column('notes', sa.Unicode(length=128), nullable=True),
    sa.Column('fuelType', sa.Integer(), nullable=True),
    sa.Column('registed_on', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_car', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('wxid', sa.String(length=128), nullable=True),
    sa.Column('xcxid', sa.String(length=128), nullable=True),
    sa.Column('UnionID', sa.String(length=128), nullable=True),
    sa.Column('wxName', sa.String(length=50), nullable=True),
    sa.Column('wxpicurl', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['user_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_vehicles')
    op.drop_table('user_group')
    op.drop_table('user_company')
    op.drop_table('period_fuel_rate')
    op.drop_table('fuel_type')
    op.drop_table('fuel_rate')
    op.drop_table('fuel_history')
    op.drop_table('fuel_his_pic')
    op.drop_table('fs_history')
    op.drop_table('company_vehicle')
    op.drop_table('company')
    op.drop_table('clients')
    op.drop_table('client_system')
    # ### end Alembic commands ###
