"""empty message

Revision ID: 8f1891d1bc98
Revises: edcf652b7c51
Create Date: 2018-10-11 16:35:33.435125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1891d1bc98'
down_revision = 'edcf652b7c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_billboard', sa.Column('client_nick', sa.Unicode(length=60), nullable=True))
    op.add_column('fuel_billboard_dtl', sa.Column('client_uid', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fuel_billboard_dtl', 'client_uid')
    op.drop_column('fuel_billboard', 'client_nick')
    # ### end Alembic commands ###
