"""empty message

Revision ID: cf8e45aa7c52
Revises: 6bd48e0fc364
Create Date: 2018-10-11 15:59:19.982704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8e45aa7c52'
down_revision = '6bd48e0fc364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_billboard',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('share_uid', sa.String(length=128), nullable=True),
    sa.Column('created_user_uid', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_billboard_dtl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billboard_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fuel_billboard_dtl')
    op.drop_table('fuel_billboard')
    # ### end Alembic commands ###
