"""empty message

Revision ID: edcf652b7c51
Revises: cf8e45aa7c52
Create Date: 2018-10-11 16:32:34.748286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edcf652b7c51'
down_revision = 'cf8e45aa7c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_billboard', sa.Column('client_id', sa.Integer(), nullable=True))
    op.add_column('fuel_billboard', sa.Column('client_uid', sa.String(length=128), nullable=True))
    op.drop_column('fuel_billboard', 'created_user_uid')
    op.drop_column('fuel_billboard', 'created_user_id')
    op.add_column('fuel_billboard_dtl', sa.Column('client_nick', sa.String(length=60), nullable=True))
    op.add_column('fuel_billboard_dtl', sa.Column('fuel_rate', sa.Float(), nullable=True))
    op.add_column('fuel_billboard_dtl', sa.Column('vehicle_name', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fuel_billboard_dtl', 'vehicle_name')
    op.drop_column('fuel_billboard_dtl', 'fuel_rate')
    op.drop_column('fuel_billboard_dtl', 'client_nick')
    op.add_column('fuel_billboard', sa.Column('created_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('fuel_billboard', sa.Column('created_user_uid', mysql.VARCHAR(collation=u'utf8mb4_unicode_ci', length=128), nullable=True))
    op.drop_column('fuel_billboard', 'client_uid')
    op.drop_column('fuel_billboard', 'client_id')
    # ### end Alembic commands ###
